# Generated by Django 4.2 on 2024-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndustrialDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.IntegerField()),
                (
                    "registration_date",
                    models.DateField(verbose_name="Дата регистрации"),
                ),
                ("application_number", models.IntegerField()),
                ("application_date", models.DateField(verbose_name="Дата публикации")),
                ("authors", models.CharField(max_length=500, verbose_name="Авторы")),
                (
                    "authors_in_latin",
                    models.CharField(max_length=500, verbose_name="Авторы на латинице"),
                ),
                (
                    "patent_holders",
                    models.CharField(max_length=500, verbose_name="Держатели патента"),
                ),
                (
                    "patent_holders_in_latin",
                    models.CharField(
                        max_length=500, verbose_name="Держатели патента на латинице"
                    ),
                ),
                (
                    "correspondence_address",
                    models.CharField(max_length=500, verbose_name="Почтовый адрес"),
                ),
                (
                    "correspondence_address_in_latin",
                    models.CharField(
                        max_length=500, verbose_name="Почтовый адрес на латинице"
                    ),
                ),
                (
                    "industrial_design_name",
                    models.CharField(max_length=500, verbose_name="Название"),
                ),
                ("patent_starting_date", models.DateField()),
                (
                    "Crimean_industrial_design_application_number_for_state_registration_in_Ukraine",
                    models.CharField(max_length=100),
                ),
                (
                    "Crimean_industrial_design_application_date_for_state_registration_in_Ukraine",
                    models.DateField(),
                ),
                (
                    "Crimean_industrial_design_patent_number_in_Ukraine",
                    models.CharField(max_length=100),
                ),
                ("receipt_date_of_additional_data_to_application", models.DateField()),
                (
                    "date_of_application_to_which_additional_data_has_been_received",
                    models.DateField(),
                ),
                (
                    "number_of_application_to_which_additional_data_has_been_received",
                    models.CharField(max_length=100),
                ),
                ("initial_application_number", models.CharField(max_length=100)),
                ("initial_application_date", models.DateField()),
                ("initial_application_priority_date", models.DateField()),
                ("previous_application_number", models.CharField(max_length=100)),
                ("previous_application_date", models.DateField()),
                ("paris_convention_priority_number", models.CharField(max_length=100)),
                ("paris_convention_priority_date", models.DateField()),
                (
                    "paris_convention_priority_country_code",
                    models.CharField(max_length=100),
                ),
                ("patent_grant_publish_date", models.DateField()),
                ("patent_grant_publish_number", models.IntegerField()),
                ("revoked_patent_number", models.IntegerField()),
                ("expiration_date", models.DateField()),
                (
                    "numbers_of_list_of_essential_features_for_which_patent_term_is_prolonged",
                    models.CharField(max_length=100),
                ),
                (
                    "industrial_designs_names_and_number_for_which_patent_term_is_prolonged",
                    models.CharField(max_length=10),
                ),
                ("actual", models.CharField(max_length=100)),
                ("publication_URL", models.CharField(max_length=1024)),
                ("actual_date", models.DateField()),
                ("mkpo", models.CharField(max_length=10)),
            ],
        ),
    ]
