# Generated by Django 4.2 on 2024-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industrialdesign",
            name="Crimean_industrial_design_application_date_for_state_registration_in_Ukraine",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="Crimean_industrial_design_application_number_for_state_registration_in_Ukraine",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="Crimean_industrial_design_patent_number_in_Ukraine",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="actual_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="date_of_application_to_which_additional_data_has_been_received",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="expiration_date",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="industrial_designs_names_and_number_for_which_patent_term_is_prolonged",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="initial_application_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="initial_application_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="initial_application_priority_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="mkpo",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="number_of_application_to_which_additional_data_has_been_received",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="numbers_of_list_of_essential_features_for_which_patent_term_is_prolonged",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="paris_convention_priority_country_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="paris_convention_priority_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="paris_convention_priority_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="patent_grant_publish_date",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="patent_grant_publish_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="patent_starting_date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="previous_application_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="previous_application_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="publication_URL",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="receipt_date_of_additional_data_to_application",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="revoked_patent_number",
            field=models.IntegerField(null=True),
        ),
    ]
