# Generated by Django 4.2 on 2024-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "patent",
            "0002_alter_industrialdesign_crimean_industrial_design_application_date_for_state_registration_in_ukraine_",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="industrialdesign",
            name="previous_application_date",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
