# Generated by Django 4.2 on 2024-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patent", "0003_alter_industrialdesign_previous_application_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industrialdesign",
            name="paris_convention_priority_date",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="industrialdesign",
            name="previous_application_date",
            field=models.DateField(null=True),
        ),
    ]
